networks:
  korp-network:
    driver: bridge

services:
  http-server-projeto-korp:
    build: .
    container_name: http-server-projeto-korp
    networks:
      - korp-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - korp-network
    depends_on:
      - http-server-projeto-korp

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - korp-network
    depends_on:
      - http-server-projeto-korp

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - korp-network
    depends_on:
      - prometheus
